seed: 0
sentence_length: 5
num_folds: 5
max_length: 512
model_ckpt_berta: "google/gemma-2b"
lbl:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
epoch: 10
batch_size: 3
model_dir: "prl90777/"
stride: 25
pad_to_multiple_of: 8
early_stopping_patience: 2
warmup_steps: 500
gradient_accumulation_steps: 8